server:
  port: 8082


keycloak:
  auth-server-url: https://auth-dev.geofacets.com/auth/
  realm: master
  resource: demo-gefacets
  public-client: true
#keycloak.security-constraints[0].authRoles[0]=ROLE_User
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/tasks
  principal-attribute: preferred_username
